import type { Landmark } from './types';

export const INTRO_LANDMARK: Landmark = {
  id: 0,
  name: "Introduction",
  title: "YOUR JOURNEY AWAITS",
  description: "Are you ready to embark on an unforgettable interactive adventure? Discover stunning landmarks, uncover hidden stories, and explore breathtaking landscapes. Click 'Start Journey' to begin.",
  imageUrl: 'https://picsum.photos/id/1015/1200/800',
  coords: [30.8, 36.5], // Center of Jordan view
  iconType: 'monument', // Not displayed, but required by type
};

export const FALLBACK_LANDMARKS: Landmark[] = [
  INTRO_LANDMARK,
  {
    id: 1,
    name: 'Amman Citadel',
    title: "AMMAN CITADEL",
    description: "Explore ancient ruins overlooking the capital. The Citadel, known in Arabic as Jabal al-Qal'a, includes remains from the Roman, Byzantine, and Umayyad periods, most notably the Temple of Hercules and the Umayyad Palace.",
    imageUrl: 'https://picsum.photos/id/101/1200/800',
    coords: [31.9566, 35.9457],
    iconType: 'monument',
  },
  {
    id: 2,
    name: 'Roman Theater, Amman',
    title: "ROMAN THEATER",
    description: "A beautifully restored 2nd-century Roman amphitheater in the heart of Amman. With a seating capacity of 6,000, this impressive structure is still used for cultural performances today.",
    imageUrl: 'https://picsum.photos/id/1016/1200/800',
    coords: [31.9515, 35.9396],
    iconType: 'monument',
    quiz: [
      {
        question: 'What is the seating capacity of the Roman Theater in Amman?',
        type: 'multiple-choice',
        options: [
          { text: '2,000', isCorrect: false },
          { text: '6,000', isCorrect: true },
          { text: '10,000', isCorrect: false },
          { text: '15,000', isCorrect: false },
        ],
      },
    ],
    block_navigation: true,
  },
  {
    id: 3,
    name: 'Jerash',
    title: "THE ROMAN CITY OF JERASH",
    description: "Wander through one of the best-preserved Roman provincial cities outside of Italy. Its colonnaded streets, grand temples, and impressive arches offer a stunning glimpse into the past.",
    imageUrl: 'https://picsum.photos/id/1027/1200/800',
    coords: [32.2808, 35.8941],
    iconType: 'monument',
  },
  {
    id: 4,
    name: 'Madaba',
    title: "THE MOSAIC MAP",
    description: "Our journey continues to Madaba, renowned for its Byzantine mosaics. Its crown jewel is the 6th-century mosaic map of the Holy Land, housed in the Greek Orthodox Church of St. George.",
    imageUrl: 'https://picsum.photos/id/103/1200/800',
    coords: [31.7176, 35.7932],
    iconType: 'monument',
  },
  {
    id: 5,
    name: 'Mount Nebo',
    title: "THE PROPHET'S VIEW",
    description: "From the summit of Mount Nebo, it is said that Moses saw the Promised Land. The site offers panoramic views stretching across the Dead Sea to the distant hills of Jerusalem.",
    imageUrl: 'https://picsum.photos/id/1043/1200/800',
    coords: [31.7667, 35.7250],
    iconType: 'nature',
  },
  {
    id: 6,
    name: 'Kerak Castle',
    title: "CRUSADER FORTRESS",
    description: "A dark labyrinth of stone-vaulted halls, Kerak Castle is a formidable reminder of the region's Crusader past. This 12th-century fortress offers breathtaking views of the surrounding valleys.",
    imageUrl: 'https://picsum.photos/id/10/1200/800',
    coords: [31.1800, 35.7000],
    iconType: 'monument',
    quiz: [
      {
        question: 'في أي قرن تم بناء قلعة الكرك الصليبية بشكل أساسي؟',
        type: 'multiple-choice',
        options: [
          { text: 'القرن العاشر', isCorrect: false },
          { text: 'القرن الثاني عشر', isCorrect: true },
          { text: 'القرن الرابع عشر', isCorrect: false },
          { text: 'القرن السادس عشر', isCorrect: false },
        ],
      },
    ],
    block_navigation: true,
  },
  {
    id: 7,
    name: 'Dana Biosphere Reserve',
    title: "FROM PEAKS TO PLAINS",
    description: "Jordan's largest nature reserve, Dana, is a world of breathtaking beauty. The landscape drops from high plateaus to desert lowlands, encompassing a spectacular diversity of wildlife and terrain.",
    imageUrl: 'https://picsum.photos/id/14/1200/800',
    coords: [30.6833, 35.6167],
    iconType: 'nature',
  },
  {
    id: 8,
    name: 'Petra',
    title: "THE ROSE-RED CITY",
    description: "The jewel in Jordan's crown. The ancient Nabatean city of Petra, half-built and half-carved into rose-red cliffs, is a UNESCO World Heritage Site and a wonder of the world.",
    imageUrl: 'https://picsum.photos/id/20/1200/800',
    coords: [30.3285, 35.4444],
    iconType: 'monument',
    videoUrl: 'https://www.youtube.com/watch?v=2rbe76sRf_c',
    audioUrl: 'https://aistudiocdn.com/Makersuite/Samples/petra_ambience.mp3',
  },
  {
    id: 9,
    name: 'Wadi Rum',
    title: "VALLEY OF THE MOON",
    description: "A vast, silent, and timeless desert valley. With its monolithic rockscapes and stunning red sands, Wadi Rum's dramatic scenery has served as the backdrop for many epic films.",
    imageUrl: 'https://picsum.photos/id/22/1200/800',
    coords: [29.5321, 35.4198],
    iconType: 'nature',
  },
  {
    id: 10,
    name: 'Dead Sea',
    title: "THE LOWEST POINT ON EARTH",
    description: "Experience the unique sensation of floating effortlessly in the hypersaline waters of the Dead Sea. Its mineral-rich mud is famous for its therapeutic properties.",
    imageUrl: 'https://picsum.photos/id/24/1200/800',
    coords: [31.5590, 35.4732],
    iconType: 'water',
  },
  {
    id: 11,
    name: 'Aqaba',
    title: "GATEWAY TO THE RED SEA",
    description: "Jordan's only coastal city, Aqaba is a vibrant hub for diving and snorkeling. Its clear waters are home to stunning coral reefs and a rich diversity of marine life.",
    imageUrl: 'https://picsum.photos/id/25/1200/800',
    coords: [29.5326, 35.0063],
    iconType: 'water',
  },
  {
    id: 12,
    name: 'Qasr Amra',
    title: "UMAYYAD DESERT CASTLE",
    description: "A UNESCO World Heritage site, this 8th-century desert castle is one of the most important examples of early Islamic art and architecture, famous for its unique and vivid frescoes.",
    imageUrl: 'https://picsum.photos/id/30/1200/800',
    coords: [31.8006, 36.5761],
    iconType: 'monument',
  },
];